/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateMeeting from "./functions/create_meeting.ts";

const Zoom = {
  functions: {
    /**
     * @memberOf Connectors.Zoom.functions
     * @param {object} options - CreateMeeting input options object.
     * @param {string} options.topic - Enter a meeting title...
     * @param {string} [options.agenda] - Enter an agenda...
     * @param {string[]} options.invitees - Search all people...
     * @param {object} options.zoom_access_token -
     * @param {"DEVELOPER"|"END_USER"} options.zoom_access_token.credential_source - specifies which user’s token should be selected
     */ CreateMeeting,
  },
} as const;

export default Zoom;
