/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import AddSpreadsheetRow from "./functions/add_spreadsheet_row.ts";

const GoogleSheets = {
  functions: {
    /**
     * @memberOf Connectors.GoogleSheets.functions
     * @param {object} options - AddSpreadsheetRow input options object.
     * @param {string} options.spreadsheet_id - Select a spreadsheet
     * @param {string} options.sheet_title - Select a sheet
     * @param {object} options.columns - Columns
     * @param {object} options.google_access_token - Whose account should be adding rows to the spreadsheet?
     * @param {"DEVELOPER"|"END_USER"} options.google_access_token.credential_source - specifies which user’s token should be selected
     */ AddSpreadsheetRow,
  },
} as const;

export default GoogleSheets;
