/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";

const GithubCloud = {
  functions: {
    /**
     * @memberOf Connectors.GithubCloud.functions
     * @param {object} options - CreateIssue input options object.
     * @param {string} options.repository - Select a GitHub repository
     * @param {string} options.title - Enter an issue title...
     * @param {string} [options.description] - Enter a description...
     * @param {object} options.github_access_token - GitHub Credential to use
     * @param {"DEVELOPER"|"END_USER"} options.github_access_token.credential_source - specifies which user’s token should be selected
     */ CreateIssue,
  },
} as const;

export default GithubCloud;
