/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import CreateIssue from "./functions/create_issue.ts";

const Gitlab = {
  functions: {
    /**
     * @memberOf Connectors.Gitlab.functions
     * @param {object} options - CreateIssue input options object.
     * @param {string} options.project_id - The ID of the project where the issue is created
     * @param {string} options.title - Enter an issue title...
     * @param {string} [options.description] - Enter a description...
     * @param {string} options.issue_type - The type of issue. Valid options are: issue or incident
     * @param {string} [options.milestone_id] - The Global ID of a milestone to assign the issue
     * @param {boolean} options.confidential - Set the issue to be confidential and only be visible to team members with at least reporter access
     * @param {object} options.gitlab_access_token -
     * @param {"DEVELOPER"|"END_USER"} options.gitlab_access_token.credential_source - specifies which user’s token should be selected
     */ CreateIssue,
  },
} as const;

export default Gitlab;
