/** This file was autogenerated. Follow the steps in src/schema/slack/functions/README.md to rebuild **/
import GetMeetingLink from "./functions/get_meeting_link.ts";

const Calendly = {
  functions: {
    /**
     * @memberOf Connectors.Calendly.functions
     * @param {object} options - GetMeetingLink input options object.
     * @param {string} options.calendly_user -
     * @param {string} options.event_type -
     * @param {object} options.calendly_access_token - Calendly credential to use
     * @param {"DEVELOPER"|"END_USER"} options.calendly_access_token.credential_source - specifies which user’s token should be selected
     */ GetMeetingLink,
  },
} as const;

export default Calendly;
